name: swiftsimio

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - black
  - h5py
  - ipython
  - matplotlib
  - numba>=0.60
  - numpy>=2.0
  - pip
  - pykdtree
  - pytest
  - scipy
  - tqdm
  - unyt
  - pip:
    - h5glance
    - py-sphviewer
    - swiftsimio
    - velociraptor
    - wily
