name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install uv
        uv pip install --system flake8 pytest
        if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi
        if [ -f optional_requirements.txt ]; then uvpip install --system -r optional_requirements.txt; fi
        uv pip install --system -e .
    - name: Test with pytest
      run: |
        pytest
      env:
        NUMBA_BOUNDSCHECK: 1
